### ISSUE TITLE
[Feat] SignUp Page

### ISSUE THREAD

**Issue by xmun74** [four-uncles/saramara-community-client#7]
## Description

- 회원가입 페이지

## Todo

- [x]  UI 단
- [x]  API 연결
- [x]  유효성 검사
   - [x] 이메일 유효성 : test@email.com 이메일 형식 준수. 필수값
   - [x] 닉네임 유효성 : 3자 이상. 필수값
   - [x] 비밀번호 유효성 : 6자 이상 18자 이하. 필수값
   - [x] 비밀번호 확인 : 비밀번호와 일치해야함. 필수값

## 스크린샷

- 
<img width="1495" alt="image" src="https://github.com/four-uncles/saramara-community-client/assets/77045939/9e8e021c-0c4f-47b9-b334-a412f553d19d">

**Comment by langoustinee** [comment]
서버 저장소에서는 `[Feat] 타이틀 내용..` 으로 작성중인데, 여기도 컨벤션을 통일하는 것은 어떨까요?

**Comment by xmun74** [comment]
`/api/v1/member` 회원가입 API 서버 테스트 필요
